import type { ThemeColors } from './types';

// ============ 布局常量 ============
export const HEADER_WIDTH = 52;
export const HEADER_HEIGHT = 24;
export const DEFAULT_COL_WIDTH = 100;
export const DEFAULT_ROW_HEIGHT = 24;
export const MIN_COL_WIDTH = 30;
export const MIN_ROW_HEIGHT = 24;
export const MAX_COL_WIDTH = 1000;
export const MAX_ROW_HEIGHT = 500;

// ============ 滚动条常量 ============
export const SB_SIZE = 11;
export const ARROW_SIZE = 11;
export const SCROLL_STEP = 50;

// ============ 撤销/重做 ============
export const UNDO_MAX = 50;

// ============ 国际化文本 ============
export const i18n: Record<string, Record<string, string>> = {
  'zh-CN': {
    insert: '插入',
    delete: '删除',
    rename: '重命名',
    moveLeft: '左移',
    moveRight: '右移',
    cut: '剪切',
    copy: '复制',
    paste: '粘贴',
    addSheet: '新建工作表',
    moveSheetLeft: '左移',
    moveSheetRight: '右移',
    scrollUp: '向上滚动',
    scrollDown: '向下滚动',
    scrollLeft: '向左滚动',
    scrollRight: '向右滚动',
    calculate: '计算',
    sum: '求和',
    undo: '撤销',
    redo: '重做',
    paintFormat: '格式刷',
    clearFormat: '清除格式',
    fontFamily: '字体',
    fontSize: '字号',
    fontSizeIncrease: '增大字号',
    fontSizeDecrease: '减小字号',
    bold: '加粗',
    italic: '斜体',
    underline: '下划线',
    strikethrough: '删除线',
    fontColor: '文字颜色',
    fillColor: '填充颜色',
    borders: '边框',
    hAlign: '水平对齐',
    vAlign: '垂直对齐',
    alignLeft: '左端对齐',
    alignCenter: '居中对齐',
    alignRight: '右端对齐',
    alignTop: '顶端对齐',
    alignMiddle: '垂直居中',
    alignBottom: '底端对齐',
    wrap: '自动换行',
    borderBottom: '下框线',
    borderTop: '上框线',
    borderLeft: '左框线',
    borderRight: '右框线',
    borderNone: '无框线',
    borderAll: '所有框线',
    borderOuter: '外框线',
    borderThickOuter: '粗外框线',
    fontDefault: '默认',
    rowHeight: '行高',
    colWidth: '列宽',
    autoRowHeight: '自动行高',
    defaultColWidth: '默认列宽',
    ok: '确定',
    cancel: '取消',
    dimNumberError: '请输入数字',
    dimRangeError: '请输入 {min}~{max} 之间的数值',
    colorAutomatic: '自动',
    colorNoFill: '无填充',
    colorWhite: '白色',
    colorBlack: '黑色',
    colorLightGray: '浅灰',
    colorLightBlue: '浅蓝',
    colorLightOrange: '浅橙',
    colorLightYellow: '浅黄',
    colorLightGreen: '浅绿',
    colorPaleBlue: '淡蓝',
    colorPaleOrange: '淡橙',
    colorPaleYellow: '淡黄',
    colorPaleGreen: '淡绿',
    colorSilver: '银色',
    colorSkyBlue: '天蓝',
    colorCoral: '珊瑚',
    colorGold: '金色',
    colorMint: '薄荷',
    colorGray: '灰色',
    colorMediumBlue: '中蓝',
    colorOrange: '橙色',
    colorAmber: '琥珀',
    colorMediumGreen: '中绿',
    colorDarkGray: '深灰',
    colorRoyalBlue: '宝蓝',
    colorRed: '红色',
    colorDarkGold: '深金',
    colorDarkGreen: '深绿',
    colorCharcoal: '炭灰',
    colorDeepBlue: '深蓝',
    colorDarkRed: '深红',
    colorOlive: '橄榄',
    colorForest: '森林',
    colorSlate: '石板灰',
    colorNavy: '藏青',
    colorCrimson: '绯红',
    colorDarkOlive: '深橄榄',
    colorDeepForest: '深林',
    colorDarkSlate: '深石板灰',
    colorMidnight: '午夜蓝',
    colorMaroon: '栗色',
    colorCoffee: '咖啡色',
    colorEvergreen: '常青',
    colorDarkNavy: '深藏青',
    colorDarkMaroon: '深栗',
    colorDarkCoffee: '深咖',
    colorInkGreen: '墨绿',
  },
  'en-US': {
    insert: 'Insert',
    delete: 'Delete',
    rename: 'Rename',
    moveLeft: 'Move Left',
    moveRight: 'Move Right',
    cut: 'Cut',
    copy: 'Copy',
    paste: 'Paste',
    addSheet: 'Add new sheet',
    moveSheetLeft: 'Move Left',
    moveSheetRight: 'Move Right',
    scrollUp: 'Scroll up',
    scrollDown: 'Scroll down',
    scrollLeft: 'Scroll left',
    scrollRight: 'Scroll right',
    calculate: 'Calculate',
    sum: 'Sum',
    undo: 'Undo',
    redo: 'Redo',
    paintFormat: 'Paint Format',
    clearFormat: 'Clear Format',
    fontFamily: 'Font Family',
    fontSize: 'Font Size',
    fontSizeIncrease: 'Increase Font Size',
    fontSizeDecrease: 'Decrease Font Size',
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strikethrough: 'Strikethrough',
    fontColor: 'Font Color',
    fillColor: 'Fill Color',
    borders: 'Borders',
    hAlign: 'Horizontal Align',
    vAlign: 'Vertical Align',
    alignLeft: 'Align Left',
    alignCenter: 'Align Center',
    alignRight: 'Align Right',
    alignTop: 'Align Top',
    alignMiddle: 'Align Middle',
    alignBottom: 'Align Bottom',
    wrap: 'Wrap Text',
    borderBottom: 'Bottom Border',
    borderTop: 'Top Border',
    borderLeft: 'Left Border',
    borderRight: 'Right Border',
    borderNone: 'No Border',
    borderAll: 'All Borders',
    borderOuter: 'Outside Borders',
    borderThickOuter: 'Thick Box Border',
    fontDefault: 'Default',
    rowHeight: 'Row Height',
    colWidth: 'Column Width',
    autoRowHeight: 'Auto Row Height',
    defaultColWidth: 'Default Column Width',
    ok: 'OK',
    cancel: 'Cancel',
    dimNumberError: 'Please enter a number',
    dimRangeError: 'Please enter a value between {min} and {max}',
    colorAutomatic: 'Automatic',
    colorNoFill: 'No Fill',
    colorWhite: 'White',
    colorBlack: 'Black',
    colorLightGray: 'Light Gray',
    colorLightBlue: 'Light Blue',
    colorLightOrange: 'Light Orange',
    colorLightYellow: 'Light Yellow',
    colorLightGreen: 'Light Green',
    colorPaleBlue: 'Pale Blue',
    colorPaleOrange: 'Pale Orange',
    colorPaleYellow: 'Pale Yellow',
    colorPaleGreen: 'Pale Green',
    colorSilver: 'Silver',
    colorSkyBlue: 'Sky Blue',
    colorCoral: 'Coral',
    colorGold: 'Gold',
    colorMint: 'Mint',
    colorGray: 'Gray',
    colorMediumBlue: 'Medium Blue',
    colorOrange: 'Orange',
    colorAmber: 'Amber',
    colorMediumGreen: 'Medium Green',
    colorDarkGray: 'Dark Gray',
    colorRoyalBlue: 'Royal Blue',
    colorRed: 'Red',
    colorDarkGold: 'Dark Gold',
    colorDarkGreen: 'Dark Green',
    colorCharcoal: 'Charcoal',
    colorDeepBlue: 'Deep Blue',
    colorDarkRed: 'Dark Red',
    colorOlive: 'Olive',
    colorForest: 'Forest',
    colorSlate: 'Slate',
    colorNavy: 'Navy',
    colorCrimson: 'Crimson',
    colorDarkOlive: 'Dark Olive',
    colorDeepForest: 'Deep Forest',
    colorDarkSlate: 'Dark Slate',
    colorMidnight: 'Midnight',
    colorMaroon: 'Maroon',
    colorCoffee: 'Coffee',
    colorEvergreen: 'Evergreen',
    colorDarkNavy: 'Dark Navy',
    colorDarkMaroon: 'Dark Maroon',
    colorDarkCoffee: 'Dark Coffee',
    colorInkGreen: 'Ink Green',
  },
};

export function t(locale: string, key: string): string {
  return i18n[locale]?.[key] ?? key;
}

// ============ 字体常量 ============
export const DEFAULT_FONT_FAMILY = '-apple-system, BlinkMacSystemFont, "Segoe UI", "Microsoft YaHei", sans-serif';
export const DEFAULT_FONT_SIZE = 10;

export interface FontOption {
  label: string;
  value: string | number;
  /** 触发器/菜单项图标，提供时以图标取代文本标签展示在触发器上 */
  icon?: string;
}

export const FONT_FAMILIES: FontOption[] = [
  { label: '', value: '' },
  { label: '微软雅黑', value: '"Microsoft YaHei", "微软雅黑", sans-serif' },
  { label: '宋体', value: '"SimSun", "宋体", serif' },
  { label: '黑体', value: '"SimHei", "黑体", sans-serif' },
  { label: '楷体', value: '"KaiTi", "楷体", serif' },
  { label: 'Arial', value: 'Arial, sans-serif' },
  { label: 'Arial Black', value: '"Arial Black", sans-serif' },
  { label: 'Times New Roman', value: '"Times New Roman", serif' },
  { label: 'Courier New', value: '"Courier New", monospace' },
  { label: 'Verdana', value: 'Verdana, sans-serif' },
  { label: 'Georgia', value: 'Georgia, serif' },
  { label: 'Impact', value: 'Impact, sans-serif' },
  { label: 'Tahoma', value: 'Tahoma, sans-serif' },
  { label: 'Trebuchet MS', value: '"Trebuchet MS", sans-serif' },
  { label: 'Comic Sans MS', value: '"Comic Sans MS", cursive' },
];

export const FONT_SIZES: FontOption[] = [
  { label: '9', value: 9 },
  { label: '10', value: 10 },
  { label: '11', value: 11 },
  { label: '12', value: 12 },
  { label: '13', value: 13 },
  { label: '14', value: 14 },
  { label: '16', value: 16 },
  { label: '18', value: 18 },
  { label: '20', value: 20 },
  { label: '24', value: 24 },
  { label: '28', value: 28 },
  { label: '32', value: 32 },
  { label: '36', value: 36 },
  { label: '48', value: 48 },
  { label: '72', value: 72 },
];

// ============ 对齐选项 ============
// 图标统一 1:1 (viewBox 24x24)、无外框，仅以线条示意对齐方向
export interface AlignOption {
  value: string;
  labelKey: string;
  icon: string;
}

const H_ALIGN_LEFT_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="19" y2="6"/><line x1="3" y1="12" x2="15" y2="12"/><line x1="3" y1="18" x2="17" y2="18"/></svg>';
const H_ALIGN_CENTER_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="6" y1="12" x2="18" y2="12"/><line x1="4" y1="18" x2="20" y2="18"/></svg>';
const H_ALIGN_RIGHT_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="5" y1="6" x2="21" y2="6"/><line x1="9" y1="12" x2="21" y2="12"/><line x1="7" y1="18" x2="21" y2="18"/></svg>';

// 垂直对齐：三条竖线（中间稍短），顶端/底端对齐附加横线（与竖线留间距）
const V_ALIGN_TOP_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="6" y1="7" x2="6" y2="20"/><line x1="12" y1="7" x2="12" y2="16"/><line x1="18" y1="7" x2="18" y2="20"/><line x1="4" y1="3" x2="20" y2="3"/></svg>';
const V_ALIGN_MIDDLE_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="6" y1="4" x2="6" y2="20"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="18" y1="4" x2="18" y2="20"/></svg>';
const V_ALIGN_BOTTOM_ICON = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="6" y1="4" x2="6" y2="17"/><line x1="12" y1="8" x2="12" y2="17"/><line x1="18" y1="4" x2="18" y2="17"/><line x1="4" y1="21" x2="20" y2="21"/></svg>';

export const H_ALIGN_OPTIONS: AlignOption[] = [
  { value: 'left', labelKey: 'alignLeft', icon: H_ALIGN_LEFT_ICON },
  { value: 'center', labelKey: 'alignCenter', icon: H_ALIGN_CENTER_ICON },
  { value: 'right', labelKey: 'alignRight', icon: H_ALIGN_RIGHT_ICON },
];

export const V_ALIGN_OPTIONS: AlignOption[] = [
  { value: 'top', labelKey: 'alignTop', icon: V_ALIGN_TOP_ICON },
  { value: 'middle', labelKey: 'alignMiddle', icon: V_ALIGN_MIDDLE_ICON },
  { value: 'bottom', labelKey: 'alignBottom', icon: V_ALIGN_BOTTOM_ICON },
];

export const WRAP_ICON = '<svg viewBox="0 0 1024 1024" fill="currentColor"><path d="M896 179.2a38.4 38.4 0 0 0-76.8 0v665.6a38.4 38.4 0 0 0 76.8 0v-665.6zM204.8 281.6A38.4 38.4 0 0 0 204.8 358.4h179.2a38.4 38.4 0 0 0 0-76.8H204.8zM550.4 281.6a38.4 38.4 0 0 0 0 76.8h51.2c35.328 0 64 28.672 64 64v179.2c0 35.328-28.672 64-64 64H246.272l36.864-36.864a38.4 38.4 0 1 0-54.272-54.272l-102.4 102.4a38.4 38.4 0 0 0 0 54.272l102.4 102.4a38.4 38.4 0 0 0 54.272-54.272l-36.864-36.864h355.328a140.8 140.8 0 0 0 140.8-140.8v-179.2a140.8 140.8 0 0 0-140.8-140.8h-51.2z" /></svg>';


// ============ 主题色盘 ============
export const lightTheme: ThemeColors = {
  bg: '#f4f4f4',
  gridBg: '#ffffff',
  headerBg: '#e8e8e8',
  headerBorder: '#c8c8c8',
  headerText: '#444',
  headerSep: '#b0b0b0',
  cornerBg: '#e0e0e0',
  gridLine: '#e0e0e0',
  selectionBg: 'rgba(0, 120, 215, 0.12)',
  activeCellBorder: '#0078d7',
  cellText: '#1a1a1a',
  scrollTrack: 'rgba(0,0,0,0.08)',
  scrollThumb: 'rgba(0,0,0,0.25)',
  formulaBarBg: '#f0f0f0',
  formulaBarBorder: '#c8c8c8',
  formulaBarLabelText: '#333',
  formulaBarLabelBg: '#fff',
  formulaBarLabelBorder: '#c0c0c0',
  formulaBarInputBg: '#fff',
  formulaBarInputBorder: '#c0c0c0',
  formulaBarInputText: '#1a1a1a',
  formulaBarInputFocusBorder: '#0078d7',
  formulaBarInputFocusShadow: 'rgba(0, 120, 215, 0.3)',
  wrapperBg: '#e8e8e8',
  cellEditorBorder: '#0078d7',
  cellEditorText: '#1a1a1a',
  cellEditorBg: '#fff',
  cellEditorShadow: '#0078d7',
  tabBarBg: '#e8e8e8',
  tabBarBorder: '#c0c0c0',
  tabActiveBg: '#ffffff',
  tabActiveText: '#1a1a1a',
  tabActiveBorder: '#0078d7',
  tabInactiveBg: '#dfdfdf',
  tabInactiveText: '#666',
  tabInactiveBorder: 'transparent',
  tabHoverBg: '#e0e0e0',
  tabAddBtnColor: '#555',
  tabAddBtnHoverBg: '#d0d0d0',
  tabScrollBtnColor: '#888',
  tabScrollBtnHoverBg: '#d0d0d0',
  scrollbarThumb: 'rgba(0,0,0,0.25)',
  scrollbarThumbHover: 'rgba(0,0,0,0.4)',
  scrollBtnBg: '#e8e8e8',
  scrollBtnColor: '#666',
  scrollBtnHoverBg: '#d0d0d0',
  scrollBtnActiveBg: '#c0c0c0',
  scrollTrackBg: 'rgba(0,0,0,0.06)',
  toolbarBg: '#f7f7f7',
  toolbarBorder: '#d8d8d8',
  toolbarBtnColor: '#444',
  toolbarBtnHoverBg: '#e6e6e6',
  toolbarBtnDisabledColor: '#b0b0b0',
  toolbarBtnActiveColor: '#0078d7',
};

export const darkTheme: ThemeColors = {
  bg: '#1e1e1e',
  gridBg: '#252526',
  headerBg: '#252525',
  headerBorder: '#3e3e3e',
  headerText: '#999',
  headerSep: '#3e3e3e',
  cornerBg: '#2a2a2a',
  gridLine: '#3e3e3e',
  selectionBg: 'rgba(0, 120, 215, 0.25)',
  activeCellBorder: '#0078d7',
  cellText: '#d4d4d4',
  scrollTrack: 'rgba(255,255,255,0.06)',
  scrollThumb: 'rgba(255,255,255,0.2)',
  formulaBarBg: '#2d2d2d',
  formulaBarBorder: '#3e3e3e',
  formulaBarLabelText: '#ccc',
  formulaBarLabelBg: '#3c3c3c',
  formulaBarLabelBorder: '#555',
  formulaBarInputBg: '#3c3c3c',
  formulaBarInputBorder: '#555',
  formulaBarInputText: '#d4d4d4',
  formulaBarInputFocusBorder: '#0078d7',
  formulaBarInputFocusShadow: 'rgba(0, 120, 215, 0.4)',
  wrapperBg: '#1e1e1e',
  cellEditorBorder: '#0078d7',
  cellEditorText: '#d4d4d4',
  cellEditorBg: '#3c3c3c',
  cellEditorShadow: '#0078d7',
  tabBarBg: '#2a2a2a',
  tabBarBorder: '#3e3e3e',
  tabActiveBg: '#1e1e1e',
  tabActiveText: '#e0e0e0',
  tabActiveBorder: '#0078d7',
  tabInactiveBg: '#333333',
  tabInactiveText: '#888',
  tabInactiveBorder: 'transparent',
  tabHoverBg: '#3a3a3a',
  tabAddBtnColor: '#999',
  tabAddBtnHoverBg: '#3a3a3a',
  tabScrollBtnColor: '#777',
  tabScrollBtnHoverBg: '#3a3a3a',
  scrollbarThumb: 'rgba(255,255,255,0.2)',
  scrollbarThumbHover: 'rgba(255,255,255,0.35)',
  scrollBtnBg: '#2d2d2d',
  scrollBtnColor: '#999',
  scrollBtnHoverBg: '#3d3d3d',
  scrollBtnActiveBg: '#4d4d4d',
  scrollTrackBg: 'rgba(255,255,255,0.05)',
  toolbarBg: '#2a2a2a',
  toolbarBorder: '#3e3e3e',
  toolbarBtnColor: '#ccc',
  toolbarBtnHoverBg: '#3a3a3a',
  toolbarBtnDisabledColor: '#666',
  toolbarBtnActiveColor: '#4ea1ff',
};
